POST http://inkubaattori.aalto.fi:5000/api/RegistrationData/CreateRegistration
Content-Type: application/json

{
    "firstName": "TestiToka",
    "lastName": "Testikolmas",
    "email": "vituttaa@inkubio.fi",
    "seatingGroup": "Gambiina",
    "alcohol": true,
    "avec": "No lol ei",
    "salute": 1,
    "invited": 1,
    "text": "Helloing of the world"
}
