POST http://localhost:5000/api/RegistrationData/CreateRegistration
Content-Type: application/json

{
    "firstName": "TestiEka",
    "lastName": "TestiToke",
    "email": "vituttaa@inkubio.fi",
    "seatingGroup": "Gambiina",
    "alcohol": true,
    "text": "Helloing of the world"
}
