POST http://localhost:5000/api/RegistrationData/CreateRegistration
Content-Type: application/json

{
    "firstName": "TestiToka",
    "lastName": "Testikolmas",
    "email": "vituttaa",
    "seatingGroup": "Gambiina",
    "alcohol": true,
    "text": "Helloing of the world"
}
